### ISSUE TITLE
Error line 17

### ISSUE THREAD

**Issue by karlosalvarado** [ParallelDevs/e_invoice_cr#11]
El error de abajo me empezó a suceder despúes de activar el módulo:

site@site.co.cr [~/facturacion.site.co.cr]# drush cron
ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in Composer\Autoload\includeFile() (line 17 of                                                           [error]
/home/site/facturacion.site.co.cr/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Entity/InvoiceEntityInterface.php) #0 /home/site/vendor/composer/ClassLoader.php(301):
Composer\Autoload\includeFile('/home/site/f...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\invoice_...')
#2 /home/site/facturacion.site.co.cr/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Entity/InvoiceEntity.php(68): spl_autoload_call('Drupal\\invoice_...')
#3 /home/site/vendor/composer/ClassLoader.php(412): include('/home/site/f...')
#4 /home/site/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/home/site/f...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\invoice_...')
#6 [internal function]: spl_autoload_call('Drupal\\invoice_...')
#7 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/EntityType.php(439): is_subclass_of('Drupal\\invoice_...', 'Drupal\\Core\\Ent...')
#8 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/EntityType.php(323): Drupal\Core\Entity\EntityType->entityClassImplements('Drupal\\Core\\Ent...')
#9 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/ContentEntityType.php(33): Drupal\Core\Entity\EntityType->__construct(Array)
#10 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/Annotation/EntityType.php(60): Drupal\Core\Entity\ContentEntityType->__construct(Array)
#11 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/Annotation/ContentEntityType.php(38): Drupal\Core\Entity\Annotation\EntityType->get()
#12 /home/site/facturacion.site.co.cr/core/lib/Drupal/Component/Annotation/Plugin/Discovery/AnnotatedClassDiscovery.php(149): Drupal\Core\Entity\Annotation\ContentEntityType->get()
#13 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/EntityTypeManager.php(106): Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery->getDefinitions()
#14 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Plugin/DefaultPluginManager.php(175): Drupal\Core\Entity\EntityTypeManager->findDefinitions()
#15 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/EntityTypeRepository.php(83): Drupal\Core\Plugin\DefaultPluginManager->getDefinitions()
#16 /home/site/facturacion.site.co.cr/core/lib/Drupal/Core/Entity/Entity.php(527): Drupal\Core\Entity\EntityTypeRepository->getEntityTypeFromClass('Drupal\\user\\Ent...')
#17 /home/site/vendor/drush/drush/lib/Drush/User/User8.php(26): Drupal\Core\Entity\Entity::load(0)
#18 /home/site/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(558): Drush\User\User8->load_by_uid(0)
#19 /home/site/vendor/drush/drush/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot->bootstrap_drupal_login()
#20 /home/site/vendor/drush/drush/includes/bootstrap.inc(473): drush_bootstrap(6, 6)
#21 /home/site/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(6)
#22 /home/site/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#23 /home/site/vendor/drush/drush/drush.php(12): drush_main()
#24 {main}.
ParseError: syntax error, unexpected &#039;const&#039; (T_CONST), expecting variable (T_VARIABLE) in Composer\Autoload\includeFile() (line 17 of /home/site/facturacion.site.co.cr/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Entity/InvoiceEntityInterface.php).
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                               [error]
Drush was not able to start (bootstrap) Drupal.                                                                                                                                                  [error]
Hint: This error can only occur once the database connection has already been successfully initiated, therefore this error generally points to a site configuration issue, and not a problem
connecting to the database.

**Comment by alarez** [comment]
Hola @karlosalvarado podrías por favor describir un poco más tu ambiente.
Versión de Drupal
Versión de PHP
Servidor?

Etc

**Comment by karlosalvarado** [comment]
Buenas tardes

Primero que todo muchas gracias por ponerse en contacto conmigo.

Adjunto el phpinfo() del sitio Web, es un:

   - Drupal 8.5.6
   - CENTOS 6.9 virtuozzo [server] v68.0.29
   - PHP 7.1.21




Karlos Alvarado

**Comment by k-vargas** [comment]
Hola @karlosalvarado el problema se presenta ya que en algunas versiones de PHP, cuando declaras una variable como _public const_, da problemas. Lo que se debe hacer es declarar simplemente la variable como _const_ y de igual manera esta por defecto se declara como variable pública.
Acabo de agregar un nuevo branch (issue_11) donde ya se realizaron esos cambios, reinstala el módulo y ya no te debería generar más problemas.
