### ISSUE TITLE
Java not detected on the server.

### ISSUE THREAD

**Issue by karlosalvarado** [ParallelDevs/e_invoice_cr#18]
Hola
Instalé Drupal 8.6.1 (sin el swiftmailer porque tengo problemas instalando la libreria swiftmailer), tengo un mensaje después de activar el módulo e_invoice_cr:

Mensaje de error
Invoice CR Module: Java not detected on the server. This module needs java installed to work properly.

En los requerimientos leí que solo necesitaba Composer para usar este modulo. ¿a qué se debe este mensaje?

Gracias

**Comment by alarez** [comment]
Realmente ese mensaje no está relacionado con swifmailer.
El problema es exactamente lo que dice el error que usted necesita Java instalado en el server.

El módulode e_invoice_cr contiene un jar que es el que se encarga de firmar los XML.

**Comment by karlosalvarado** [comment]
Muy bien, en los requerimientos no menciona que se necesita un servidor con JAVA.

Gracias

**Comment by alarez** [comment]
Tiene toda la razón. Vamos a agregarlo.

**Comment by alarez** [comment]
Información agregada al readme
