### ISSUE TITLE
Problemas para crear facturas

### ISSUE THREAD

**Issue by EstebanMonge** [ParallelDevs/e_invoice_cr#24]
Esta es mi configuración
Debian 9, PHP 7.1, Drupal 8. Cloné el git para instalar:

Al final pongo la salida del composer info
Al tratar de emitir una factura me sale este error:

``
[Fri Sep 28 23:35:35.559456 2018] [php7:notice] [pid 19428] [client 192.168.122.1:37656] TypeError: Argument 1 passed to Drupal\\invoice_entity\\Form\\InvoiceEntityForm::__construct() must implement interface Drupal\\Core\\Entity\\EntityManagerInterface, instance of Drupal\\Core\\Entity\\EntityRepository given, called in /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php on line 73 in /var/www/html/drupal/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Form/InvoiceEntityForm.php on line 37 #0 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php(73): Drupal\\invoice_entity\\Form\\InvoiceEntityForm->__construct(Object(Drupal\\Core\\Entity\\EntityRepository), Object(Drupal\\Core\\Entity\\EntityTypeBundleInfo), Object(Drupal\\Component\\Datetime\\Time))\n#1 /var/www/html/drupal/web/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php(28): Drupal\\Core\\Entity\\ContentEntityForm::create(Object(Drupal\\Core\\DependencyInjection\\Container))\n#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php(188): Drupal\\Core\\DependencyInjection\\ClassResolver->getInstanceFromDefinition('Drupal\\\\invoice_...')\n#3 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(105): Drupal\\Core\\Entity\\EntityTypeManager->getFormObject('invoice_entity', 'add')\n#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/HtmlEntityFormController.php(69): Drupal\\Core\\Entity\\EntityManager->getFormObject('invoice_entity', 'add')\n#5 /var/www/html/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(78): Drupal\\Core\\Entity\\HtmlEntityFormController->getFormObject(Object(Drupal\\Core\\Routing\\RouteMatch), 'invoice_entity....')\n#6 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\RouteMatch))\n#7 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)\n#8 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#9 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#10 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)\n#11 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#12 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#13 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#14 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#15 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#16 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#17 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#18 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#19 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(665): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/www/html/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#22 {main}, referer: http://192.168.122.186/drupal/web/admin/structure/e-invoice-cr/options
``

Salida del composer
``
alchemy/zippy                         0.4.3              Zippy, the archive manager companion
asm89/stack-cors                      1.2.0              Cross-origin resource sharing library and stack middleware
behat/mink                            dev-master d5ee350 Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver          1.3.3              Symfony2 BrowserKit driver for Mink framework
behat/mink-goutte-driver              v1.2.1             Goutte driver for Mink framework
behat/mink-selenium2-driver           dev-master f4efaf5 Selenium2 (WebDriver) driver for Mink framework
chi-teck/drupal-code-generator        1.26.2             Drupal code generator
composer/installers                   v1.6.0             A multi-framework Composer library installer
composer/semver                       1.4.2              Semver library that offers utilities, version constraint parsing and valida...
consolidation/annotated-command       2.9.1              Initialize Symfony Console commands from annotated command class methods.
consolidation/config                  1.1.0              Provide configuration services for a commandline tool.
consolidation/log                     1.0.6              Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters       3.2.1              Format text by applying transformations provided by plug-in formatters.
consolidation/robo                    1.3.1              Modern task runner
consolidation/self-update             1.1.3              Provides a self:update command for Symfony Console applications.
consolidation/site-alias              1.1.5              Template project for PHP libraries.
container-interop/container-interop   1.2.0              Promoting the interoperability of container objects (DIC, SL, etc.)
cweagans/composer-patches             1.6.5              Provides a way to patch Composer packages.
dflydev/dot-access-configuration      v1.0.3             Given a deep data structure representing a configuration, access configurat...
dflydev/dot-access-data               v1.1.0             Given a deep data structure, access data by dot notation.
dflydev/placeholder-resolver          v1.0.2             Given a data source representing key => value pairs, resolve placeholders l...
dnoegel/php-xdg-base-dir              0.1                implementation of xdg base directory specification for php
doctrine/annotations                  v1.6.0             Docblock Annotations Parser
doctrine/cache                        v1.8.0             Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.5.0             Collections Abstraction library
doctrine/common                       v2.9.0             Common Library for Doctrine projects
doctrine/event-manager                v1.0.0             Doctrine Event Manager component
doctrine/inflector                    v1.3.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking...
doctrine/lexer                        v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Pa...
doctrine/persistence                  v1.0.1             Doctrine Persistence abstractions.
doctrine/reflection                   v1.0.0             Doctrine Reflection component
dompdf/dompdf                         v0.8.2             DOMPDF is a CSS 2.1 compliant HTML to PDF converter
drupal-composer/drupal-scaffold       2.5.4              Composer Plugin for updating the Drupal scaffold files when using drupal/core
drupal/addressfield_cr                1.x-dev b375c58    My Awesome Module
drupal/coder                          8.3.1              Coder is a library to review Drupal code.
drupal/console                        1.8.0              The Drupal CLI. A tool to generate boilerplate code, interact with and debu...
drupal/console-core                   1.8.0              Drupal Console Core
drupal/console-en                     1.8.0              Drupal Console English Language
drupal/console-extend-plugin          0.9.2              Drupal Console Extend Plugin
drupal/core                           8.6.1              Drupal is an open source content management platform powering millions of w...
drupal/entity_print                   2.1.0              PDF print solution for any Drupal entity.
drupal/entity_reference_revisions     1.5.0              Adds a Entity Reference field type with revision support.
drupal/field_group                    1.0.0              Provides the field_group module.
drupal/mailsystem                     4.1.0              Mail System
drupal/paragraphs                     1.3.0              Enables the creation of Paragraphs entities.
drupal/swiftmailer                    1.0.0-beta2        Swiftmailer
drupal/twig_field_value               1.1.0              Twig filters for value(s) and label.
drush/drush                           9.4.0              Drush is a command line shell and scripting interface for Drupal, a veritab...
easyrdf/easyrdf                       0.9.1              EasyRdf is a PHP library designed to make it easy to consume and produce RDF.
egulias/email-validator               1.2.15             A library for validating emails
fabpot/goutte                         v3.2.3             A simple PHP Web Scraper
g1a/composer-test-scenarios           2.2.0              Useful scripts for testing multiple sets of Composer dependencies.
grasmash/expander                     1.0.0              Expands internal property references in PHP arrays file.
grasmash/yaml-expander                1.4.0              Expands internal property references in a yaml file.
guzzlehttp/guzzle                     6.3.3              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1             Guzzle promises library
guzzlehttp/psr7                       1.4.2              PSR-7 message implementation that also provides common utility methods
html2text/html2text                   4.0.1              Converts HTML to formatted plain text
instaclick/php-webdriver              1.4.5              PHP WebDriver for Selenium 2
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jcalderonzumba/gastonjs               v1.2.0             PhantomJS API based server for webpage automation
jcalderonzumba/mink-phantomjs-driver  v0.3.3             PhantomJS driver for Mink framework
league/container                      2.4.1              A fast and intuitive dependency injection container.
masterminds/html5                     2.3.0              An HTML5 parser and serializer.
mikey179/vfsStream                    v1.6.5             Virtual file system to mock the real file system in unit tests.
myclabs/deep-copy                     1.8.1              Create deep copies (clones) of your objects
nikic/php-parser                      v4.0.4             A PHP parser written in PHP
paragonie/random_compat               v2.0.17            PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
paralleldevs/e_invoice_cr             1.1.3              This module provides an invoice system according to the costa rican regulat...
phar-io/manifest                      1.0.1              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       1.0.1              Library for handling version information and constraints
phenx/php-font-lib                    0.5.1              A library to read, parse, export and make subsets of different types of fon...
phenx/php-svg-lib                     v0.3.2             A library to read, parse and export to PDF SVG files.
phpdocumentor/reflection-common       1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.0              With this component, a library can provide support for annotations via DocB...
phpdocumentor/type-resolver           0.4.0
phpspec/prophecy                      1.8.0              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             5.3.2              Library that provides collection, processing, and rendering functionality f...
phpunit/php-file-iterator             1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     1.0.9              Utility class for timing
phpunit/php-token-stream              2.0.2              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       6.5.13             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          5.0.10             Mock Object library for PHPUnit
psr/container                         1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/log                               1.0.2              Common interface for logging libraries
psy/psysh                             v0.9.8             An interactive shell for modern PHP.
sabberworm/php-css-parser             8.1.0              Parser for CSS Files written in PHP
sebastian/code-unit-reverse-lookup    1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                  2.1.3              Provides the functionality to compare PHP values for equality
sebastian/diff                        2.0.1              Diff implementation
sebastian/environment                 3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0              Snapshotting of global state
sebastian/object-enumerator           3.0.3              Traverses array structures and object graphs to enumerate all referenced ob...
sebastian/object-reflector            1.1.1              Allows reflection of object attributes, including inherited and non-public ...
sebastian/recursion-context           3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
squizlabs/php_codesniffer             3.3.2              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violati...
stack/builder                         v1.0.5             Builder for stack middlewares based on HttpKernelInterface.
stecman/symfony-console-completion    0.8.0              Automatic BASH completion for Symfony Console Component based applications.
swiftmailer/swiftmailer               v5.4.12            Swiftmailer, free feature-rich PHP mailer
symfony-cmf/routing                   1.4.1              Extends the Symfony2 routing component for dynamic routes and chaining seve...
symfony/browser-kit                   v4.1.4             Symfony BrowserKit Component
symfony/class-loader                  v3.4.15            Symfony ClassLoader Component
symfony/config                        v3.4.15            Symfony Config Component
symfony/console                       v3.4.15            Symfony Console Component
symfony/css-selector                  v3.4.15            Symfony CssSelector Component
symfony/debug                         v3.4.15            Symfony Debug Component
symfony/dependency-injection          v3.4.15            Symfony DependencyInjection Component
symfony/dom-crawler                   v3.4.15            Symfony DomCrawler Component
symfony/event-dispatcher              v3.4.15            Symfony EventDispatcher Component
symfony/filesystem                    v3.4.15            Symfony Filesystem Component
symfony/finder                        v3.4.15            Symfony Finder Component
symfony/http-foundation               v3.4.15            Symfony HttpFoundation Component
symfony/http-kernel                   v3.4.15            Symfony HttpKernel Component
symfony/phpunit-bridge                v3.4.15            Symfony PHPUnit Bridge
symfony/polyfill-ctype                v1.9.0             Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.9.0             Symfony polyfill for the Iconv extension
symfony/polyfill-mbstring             v1.9.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                v1.9.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72                v1.9.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                       v3.4.15            Symfony Process Component
symfony/psr-http-message-bridge       v1.1.0             PSR HTTP message bridge
symfony/routing                       v3.4.15            Symfony Routing Component
symfony/serializer                    v3.4.15            Symfony Serializer Component
symfony/translation                   v3.4.15            Symfony Translation Component
symfony/validator                     v3.4.15            Symfony Validator Component
symfony/var-dumper                    v4.1.4             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.4.15            Symfony Yaml Component
theseer/tokenizer                     1.1.0              A small library for converting tokenized PHP source code into XML and poten...
twig/twig                             v1.35.4            Twig, the flexible, fast, and secure template language for PHP
vlucas/phpdotenv                      v2.5.1             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVE...
webflo/drupal-core-require-dev        8.6.1              require-dev dependencies from drupal/core
webflo/drupal-finder                  1.1.0              Helper class to locate a Drupal installation from a given path.
webmozart/assert                      1.3.0              Assertions to validate method input/output with nice error messages.
webmozart/path-util                   2.3.0              A robust cross-platform utility for normalizing, comparing and modifying fi...
zendframework/zend-diactoros          1.8.6              PSR HTTP Message implementations
zendframework/zend-escaper            2.6.0              Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
zendframework/zend-feed               2.10.3             provides functionality for consuming RSS and Atom feeds
zendframework/zend-stdlib             3.2.1              SPL extensions, array utilities, error handlers, and more
``

**Comment by EstebanMonge** [comment]
Comenté estas líneas del archivo:
/var/www/html/drupal/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Form/InvoiceEntityForm.php
``
  //public function __construct(EntityManagerInterface $entity_manager, EntityTypeBundleInfoInterface $entity_type_bundle_info = NULL, TimeInterface $time = NULL) {
   // parent::__construct($entity_manager, $entity_type_bundle_info, $time);
   // $settings = \Drupal::config('e_invoice_cr.settings');
   // $empty = $settings->isNew();
   // if ($empty || is_null($settings)) {
   //   invoice_entity_config_error();
   // }
 // }
``

Y funcionó, pero no se que otra cosa habrá dejado de funcionar

**Comment by alarez** [comment]
Esteban clonar el git no es lo mejor.
Debería instalar con composer. Puedes revisar el readme.


## INSTALLING WITH COMPOSER

1- Edit your composer.json to add the repo

    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/ParallelDevs/e_invoice_cr"
        },
    ],
    
2- Run #composer require paralleldevs/e_invoice_cr"

**Comment by EstebanMonge** [comment]
Hola gracias por la respuesta, vieras que así lo hice.

**Comment by EstebanMonge** [comment]
![shot-2018-10-03_10-45-26](https://user-images.githubusercontent.com/1070783/46425743-b6c01c80-c6f9-11e8-820c-b0d5e971cd77.jpg)

**Comment by alarez** [comment]
Al parecer composer detecto que ya el modulo existia. Se aseguró de quitarlo antes?

**Comment by EstebanMonge** [comment]
Detecto que existía antes, porque lo instalé antes con composer, pero voy a volver a hacer la prueba y te cuento

**Comment by EstebanMonge** [comment]
Vieras que continúa el problema:
![shot-2018-10-03_11-34-18](https://user-images.githubusercontent.com/1070783/46428104-597b9980-c700-11e8-999c-6dda6ac8fa05.jpg)

Este fue el procedimiento que use para montar todo:

apt-get install apt-transport-https ca-certificates
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ stretch main" > /etc/apt/sources.list.d/php.list
apt-get update
apt-get upgrade
apt-get install linux-image-amd64 apache2 php mariadb-server libapache2-mod-php7.2 composer php7.2-mysql sudo zip unzip php7.2-xml php7.2-gd php7.2-mbstring php7.2-curl openjdk-8-jre
a2enmod rewrite
systemctl restart apache2
mysql_secure_installation
cd /root
wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
dpkg -i /root/wkhtmltox_0.12.5-1.stretch_amd64.deb
apt-get -f install
composer create-project drupal-composer/drupal-project:8.x-dev /var/www/html/drupal --stability dev --no-interaction
cd /var/www/html/drupal
composer require swiftmailer/swiftmailer:5.4.12
composer require 'drupal/swiftmailer:^1.0'
mkdir  /var/www/html/drupal/config
chown www-data.www-data /var/www/html/drupal/config
vim.tiny /etc/apache2/sites-enabled/000-default.conf
        <Directory "/var/www/html">
         AllowOverride All
        </Directory>
systemctl restart apache2
mysql -u root -pmanager
create database factura;
grant all privileges on factura.* to factura@localhost identified by 'factura';
chmod 644 /var/www/html/drupal/web/sites/default/settings.php
vim.tiny /var/www/html/drupal/composer.json
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
       {
            "type": "git",
            "url": "https://github.com/ParallelDevs/e_invoice_cr.git"
        }
    ],
composer require paralleldevs/e_invoice_cr
composer require drupal/Field_group
composer require drupal/Addressfield_cr
composer require drupal/Paragraphs
composer require drupal/Entity_print
composer require drupal/Twig_field_value

**Comment by alarez** [comment]
Estoy un poco confundido. Cual es el error que tienes ahora que sea relacionado con el módulo de factura y no con tu ambiente o Drupal en si.

**Comment by EstebanMonge** [comment]
Hola, gracias por la ayuda.

El error es con la facturación, cuando creo una factura nueva se ve este error en el navegador:
![shot-2018-10-03_11-58-44](https://user-images.githubusercontent.com/1070783/46429459-b593ed00-c703-11e8-9863-caef4342531b.jpg)

Revisando el log de /var/log/apache2/errors.log encuentro el siguiente mensaje:

[Wed Oct 03 11:58:32.397897 2018] [php7:notice] [pid 514] [client 192.168.122.1:40598] TypeError: Argument 1 passed to Drupal\\invoice_entity\\Form\\InvoiceEntityForm::__construct() must implement interface Drupal\\Core\\Entity\\EntityManagerInterface, instance of Drupal\\Core\\Entity\\EntityRepository given, called in /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php on line 73 in /var/www/html/drupal/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Form/InvoiceEntityForm.php on line 37 #0 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityForm.php(73): Drupal\\invoice_entity\\Form\\InvoiceEntityForm->__construct(Object(Drupal\\Core\\Entity\\EntityRepository), Object(Drupal\\Core\\Entity\\EntityTypeBundleInfo), Object(Drupal\\Component\\Datetime\\Time))\n#1 /var/www/html/drupal/web/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php(28): Drupal\\Core\\Entity\\ContentEntityForm::create(Object(Drupal\\Core\\DependencyInjection\\Container))\n#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php(188): Drupal\\Core\\DependencyInjection\\ClassResolver->getInstanceFromDefinition('Drupal\\\\invoice_...')\n#3 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityManager.php(105): Drupal\\Core\\Entity\\EntityTypeManager->getFormObject('invoice_entity', 'add')\n#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/HtmlEntityFormController.php(69): Drupal\\Core\\Entity\\EntityManager->getFormObject('invoice_entity', 'add')\n#5 /var/www/html/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(78): Drupal\\Core\\Entity\\HtmlEntityFormController->getFormObject(Object(Drupal\\Core\\Routing\\RouteMatch), 'invoice_entity....')\n#6 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\RouteMatch))\n#7 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)\n#8 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#9 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#10 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)\n#11 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#12 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#13 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#14 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#15 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#16 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#17 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#18 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#19 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(665): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/www/html/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#22 {main}, referer: http://192.168.122.22/drupal/web/admin/structure/e-invoice-cr/options

**Comment by k-vargas** [comment]
Hola Esteban, una pregunta,  que version de Drupal 8 estás utilizando especificamente?

**Comment by EstebanMonge** [comment]
Estoy usando la 8.6.1

**Comment by k-vargas** [comment]
Ok, perfecto.
Ya encontré cual es el fallo, dentro de poco subiré un pull request realizando la corrección de dicho error donde podrás revisarlo y verificar los cambios pertinentes.

**Comment by EstebanMonge** [comment]
Gracias que amables! estaré pendiente.

**Comment by k-vargas** [comment]
Gracias a vos más bien por notificarnos de dicho error.
En este link https://github.com/ParallelDevs/e_invoice_cr/pull/27 se encuentra el pull request donde se realiza la corrección de dicho error.
Aplicalo y avisas el resultado, si continua fallando, hazlo saber para ver que solución se le puede dar.

**Comment by EstebanMonge** [comment]
La buena y la mala...

La buena es que en efecto se arregló el problema, ya cuando hago la factura no da error, y la mala es que al darle verificar a la factura me sale otro mensaje, pero ¿no se si quieres que habra un tiquete aparte? perdonando el abuso...

**Comment by EstebanMonge** [comment]
Configuré otro ambiente, esta vez sin subdirectorios y funcionó bien. Lo único es que cuando valido las facturas dice que la fecha no debe ser superior a la fecha de hoy:

codigo, mensaje, fila, columna -53, "La fecha de emisión del comprobante electrónico no puede ser superior al día de hoy.

**Comment by EstebanMonge** [comment]
Reparé el problema de la fecha de emisión configurando la zona horaria en PHP.

Ahora el problema que me da es el siguiente:
Status Accepted. codigo, mensaje, fila, columna -53, "La hora indicada en la emisión del archivo XML no coincide con la hora oficial.", 0, 0 

A mi correo llegan tres archivos, el PDF, el XML firmado y la confirmación, la confirmación llega como un archivo en blanco.

**Comment by EstebanMonge** [comment]
Revisando los logs indica lo siguiente:

Warning: file_get_contents(/var/www/drupal/web/sites/default/files/xml_confirmation/document-1-00100001010000000007confirmation.xml): failed to open stream: No such file or directory en Drupal\swiftmailer\Plugin\Mail\SwiftMailer->attach() (línea 436 de /var/www/drupal/web/modules/contrib/swiftmailer/src/Plugin/Mail/SwiftMailer.php) 

Lo raro es que el archivo si existe:
root@drupal:/var/www/drupal/web/sites/default/files/xml_confirmation# ls
document-1-00100001010000000003confirmation.xml  document-1-00100001010000000007confirmation.xml
document-1-00100001010000000005confirmation.xml
root@drupal:/var/www/drupal/web/sites/default/files/xml_confirmation#

**Comment by k-vargas** [comment]
Ok, recibido.
Muchas gracias por notificarnos sobre dicho error, revisaré y te estaré comunicando lo más rápido posible cuando dicho error se resuelva.

**Comment by EstebanMonge** [comment]
¿No será mejorar hacer un ticket nuevo?

**Comment by k-vargas** [comment]
Si mejor!

**Comment by EstebanMonge** [comment]
Gracias por la ayuda con el request 27 se soluciona el problema
