### ISSUE TITLE
Modo de actualizar

### ISSUE THREAD

**Issue by EstebanMonge** [ParallelDevs/e_invoice_cr#26]
Estimados:

Quería hacerles una consulta, he visto que hacen cambios en el código, cuando arreglan algo le indican a las personas que desinstalen y vuelvan a instalar, lo que he visto que pasa es que no modifican la versión del módulo y cuando composer consulta el repositorio y ve que la versión no ha cambiado, no hace nada, incluso si se borra manualmente, composer va a usar el caché, en lugar de actualizar desde el git.

Sería conveniente documentar este comportamiento o modificar las versiones.

**Comment by alarez** [comment]
Hola Esteban gracias por tu interés en el proyecto.

Te cuento que como proyecto opensource la comunidad es la que contribuye para mejorar el software por lo que si vas a encontrar muchos trabajos en proceso y varios branches pero son solo eso un trabajo en proceso. Desde cada branch el autor puede hacer un pull request y si se prueba que está estable aceptamos el pull request y hacemos un release.

El código estable lo podrás ver en los releases. https://github.com/ParallelDevs/e_invoice_cr/releases
El ultimo estable es el 1.1.3

Por lo tanto apunta tu composer.json a un release estable o a la versión quieras usar.

Espero te ayude a entender el proceso.

**Comment by EstebanMonge** [comment]
Gracias por la aclaración, cierro el ticket.
