### ISSUE TITLE
La verificación  no envía el xml confirmado

### ISSUE THREAD

**Issue by EstebanMonge** [ParallelDevs/e_invoice_cr#28]
Estimados:

Gracias por todo el trabajo, me he encontrado el siguiente problema:
Status Accepted. codigo, mensaje, fila, columna -53, "La hora indicada en la emisión del archivo XML no coincide con la hora oficial.", 0, 0

A mi correo llegan tres archivos, el PDF, el XML firmado y la confirmación, la confirmación llega como un archivo en blanco.

Revisando los logs indica lo siguiente:

Warning: file_get_contents(/var/www/drupal/web/sites/default/files/xml_confirmation/document-1-00100001010000000007confirmation.xml): failed to open stream: No such file or directory en Drupal\swiftmailer\Plugin\Mail\SwiftMailer->attach() (línea 436 de /var/www/drupal/web/modules/contrib/swiftmailer/src/Plugin/Mail/SwiftMailer.php)

Lo raro es que el archivo si existe:
root@drupal:/var/www/drupal/web/sites/default/files/xml_confirmation# ls
document-1-00100001010000000003confirmation.xml document-1-00100001010000000007confirmation.xml
document-1-00100001010000000005confirmation.xml
root@drupal:/var/www/drupal/web/sites/default/files/xml_confirmation#

**Comment by k-vargas** [comment]
Hola @EstebanMonge

Con respecto al mensaje que te tira a la hora de validar la factura, se acaba de hacer un PR, específicamente el https://github.com/ParallelDevs/e_invoice_cr/pull/22 para que lo revises.

Por otro lado, en cuanto al archivo de confirmación de Hacienda que llega en blanco, anteriormente se realizo unos cambios que en teoría dan solución a ese inconveniente, revisa el https://github.com/ParallelDevs/e_invoice_cr/pull/13 específicamente en los archivos: 
modules/invoice_entity/src/Controller/InvoiceEntityController.php
modules/invoice_entity/src/InvoiceService.php

Aplícalo y avisas el resultado, si continua fallando, hazlo saber para ver que solución se le puede dar.

**Comment by EstebanMonge** [comment]
Hola!

Gracias por la ayuda brindada.

Con ambos cambios las facturas llegan completas y se elimina el problema de la fecha.

**Comment by EstebanMonge** [comment]
Hola que pena, pero el ticket lo cierran ustedes o lo cierro yo?
