### ISSUE TITLE
Envío de email sin archivos adjuntos

### ISSUE THREAD

**Issue by debadilla** [ParallelDevs/e_invoice_cr#29]
Hola, he ido instalando todo paso a paso y me ha funcionado muy bien pero me están llegado los correos sin los 3 archivos que deberían venir adjuntos. 
La configuración, para el envío de correos, que tengo es la que viene por defecto y no sé si debo hacer una configuración de más para que estos archivos se puedan adjuntar.
Muchas gracias.

**Comment by k-vargas** [comment]
Hola @debadilla podrías por favor describir un poco más tu ambiente.
Versión de Drupal
Versión de PHP
Servidor?

Etc

**Comment by alarez** [comment]
Hola @debadilla debes por favor proveer un log de errores para poder ayudarte y tambien lo que te dice @k-vargas de la descripción de tu ambiente.

**Comment by debadilla** [comment]
Versión de Drupal: 8.6.1
Versión de PHP: 7.2.1

Estos son los logs que me aparecen, espero sean de ayuda: 
#1
Message | Warning: count(): Parameter must be an array or an object that implements Countable in invoice_email_mail() (line 36 of /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/invoice_email.module) #0 /Applications/MAMP/htdocs/PruebaFactura/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(2, 'count(): Parame...', '/Applications/M...', 36, Array) #1 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/invoice_email.module(36): _drupal_error_handler(2, 'count(): Parame...', '/Applications/M...', 36, Array) #2 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(270): invoice_email_mail('invoice_validat...', Array, Array) #3 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(176): Drupal\Core\Mail\MailManager->doMail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #4 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Mail\MailManager->Drupal\Core\Mail\{closure}() #5 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(177): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #6 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/mailsystem/src/MailsystemManager.php(73): Drupal\Core\Mail\MailManager->mail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #7 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/src/EventSubscriber/InvoiceEmailEventSubscriber.php(116): Drupal\mailsystem\MailsystemManager->mail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #8 [internal function]: Drupal\invoice_email\EventSubscriber\InvoiceEmailEventSubscriber->invoiceSendEmail(Object(Drupal\invoice_email\InvoiceEmailEvent), 'event.send.emai...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #9 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Drupal\invoice_email\InvoiceEmailEvent), 'event.send.emai...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #10 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/InvoiceService.php(112): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('event.send.emai...', Object(Drupal\invoice_email\InvoiceEmailEvent)) #11 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Controller/InvoiceEntityController.php(186): Drupal\invoice_entity\InvoiceService->validateInvoiceEntity(Object(Drupal\invoice_entity\Entity\InvoiceEntity)) #12 [internal function]: Drupal\invoice_entity\Controller\InvoiceEntityController->validateInvoice('506091018003101...', '4') #13 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #14 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #16 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #17 /Applications/MAMP/htdocs/PruebaFactura/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #18 /Applications/MAMP/htdocs/PruebaFactura/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #19 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /Applications/MAMP/htdocs/PruebaFactura/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /Applications/MAMP/htdocs/PruebaFactura/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /Applications/MAMP/htdocs/PruebaFactura/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/DrupalKernel.php(665): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /Applications/MAMP/htdocs/PruebaFactura/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #28 {main}.
-- | --
#2 
Notice: Undefined index: cc in invoice_email_mail() (line 36 of /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/invoice_email.module) #0 /Applications/MAMP/htdocs/PruebaFactura/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(8, 'Undefined index...', '/Applications/M...', 36, Array) #1 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/invoice_email.module(36): _drupal_error_handler(8, 'Undefined index...', '/Applications/M...', 36, Array) #2 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(270): invoice_email_mail('invoice_validat...', Array, Array) #3 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(176): Drupal\Core\Mail\MailManager->doMail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #4 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Mail\MailManager->Drupal\Core\Mail\{closure}() #5 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(177): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #6 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/mailsystem/src/MailsystemManager.php(73): Drupal\Core\Mail\MailManager->mail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #7 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/src/EventSubscriber/InvoiceEmailEventSubscriber.php(116): Drupal\mailsystem\MailsystemManager->mail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #8 [internal function]: Drupal\invoice_email\EventSubscriber\InvoiceEmailEventSubscriber->invoiceSendEmail(Object(Drupal\invoice_email\InvoiceEmailEvent), 'event.send.emai...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #9 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Drupal\invoice_email\InvoiceEmailEvent), 'event.send.emai...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #10 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/InvoiceService.php(112): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('event.send.emai...', Object(Drupal\invoice_email\InvoiceEmailEvent)) #11 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Controller/InvoiceEntityController.php(186): Drupal\invoice_entity\InvoiceService->validateInvoiceEntity(Object(Drupal\invoice_entity\Entity\InvoiceEntity)) #12 [internal function]: Drupal\invoice_entity\Controller\InvoiceEntityController->validateInvoice('506091018003101...', '4') #13 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #14 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #16 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #17 /Applications/MAMP/htdocs/PruebaFactura/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #18 /Applications/MAMP/htdocs/PruebaFactura/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #19 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /Applications/MAMP/htdocs/PruebaFactura/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /Applications/MAMP/htdocs/PruebaFactura/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /Applications/MAMP/htdocs/PruebaFactura/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/DrupalKernel.php(665): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /Applications/MAMP/htdocs/PruebaFactura/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #28 {main}.

**Comment by alarez** [comment]
Y los logs de Drupal ?

**Comment by debadilla** [comment]
![screen shot 2018-10-09 at 4 54 07 pm](https://user-images.githubusercontent.com/44007496/46703385-0ca63000-cbe4-11e8-8501-0c659a949024.png)


User | admin
-- | --
http://localhost:8888/PruebaFactura/web/admin/structure/e-invoice-cr/validation/50609101800310133549400100001010000000503162321651/4
http://localhost:8888/PruebaFactura/web/admin/structure/e-invoice-cr/invoice_entity
Warning: count(): Parameter must be an array or an object that implements Countable in invoice_email_mail() (line 36 of /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/invoice_email.module) #0 /Applications/MAMP/htdocs/PruebaFactura/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(2, 'count(): Parame...', '/Applications/M...', 36, Array) #1 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/invoice_email.module(36): _drupal_error_handler(2, 'count(): Parame...', '/Applications/M...', 36, Array) #2 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(270): invoice_email_mail('invoice_validat...', Array, Array) #3 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(176): Drupal\Core\Mail\MailManager->doMail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #4 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Mail\MailManager->Drupal\Core\Mail\{closure}() #5 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Mail/MailManager.php(177): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #6 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/mailsystem/src/MailsystemManager.php(73): Drupal\Core\Mail\MailManager->mail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #7 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_email/src/EventSubscriber/InvoiceEmailEventSubscriber.php(116): Drupal\mailsystem\MailsystemManager->mail('invoice_email', 'invoice_validat...', 'dbadillasanchez...', 'en', Array, NULL, true) #8 [internal function]: Drupal\invoice_email\EventSubscriber\InvoiceEmailEventSubscriber->invoiceSendEmail(Object(Drupal\invoice_email\InvoiceEmailEvent), 'event.send.emai...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #9 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Drupal\invoice_email\InvoiceEmailEvent), 'event.send.emai...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #10 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/InvoiceService.php(112): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('event.send.emai...', Object(Drupal\invoice_email\InvoiceEmailEvent)) #11 /Applications/MAMP/htdocs/PruebaFactura/web/modules/contrib/e_invoice_cr/modules/invoice_entity/src/Controller/InvoiceEntityController.php(186): Drupal\invoice_entity\InvoiceService->validateInvoiceEntity(Object(Drupal\invoice_entity\Entity\InvoiceEntity)) #12 [internal function]: Drupal\invoice_entity\Controller\InvoiceEntityController->validateInvoice('506091018003101...', '4') #13 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #14 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #16 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #17 /Applications/MAMP/htdocs/PruebaFactura/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #18 /Applications/MAMP/htdocs/PruebaFactura/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #19 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /Applications/MAMP/htdocs/PruebaFactura/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /Applications/MAMP/htdocs/PruebaFactura/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /Applications/MAMP/htdocs/PruebaFactura/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /Applications/MAMP/htdocs/PruebaFactura/web/core/lib/Drupal/Core/DrupalKernel.php(665): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /Applications/MAMP/htdocs/PruebaFactura/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #28 {main}.

**Comment by alarez** [comment]
Por lo que veo estas corriendo Drupal en un subdirectorio. Te recomiendo primero correr Drupal de manera estable ya sea teniendo una configuración correcta en un subdirectorio o bien apuntar tu viertual host a la capeta correcta.

**Comment by alarez** [comment]
Ya que no hay respuesta en este issue y parece no ser relacionado con el módulo en si sino con la configuración de Drupal voy a cerrarlo.
